export enum AdminLogAction {
  SCORE_UPDATE = 'score_update',
  GAME_CREATE = 'game_create',
  GAME_DELETE = 'game_delete',
  GAME_RETIRE = 'game_retire',
  GAME_UNRETIRE = 'game_unretire',
  GAME_VISIBILITY = 'game_visibility',
  GAME_TOP3 = 'game_top3',
  TEAM_GAME_CREATE = 'team_game_create',
  TEAM_GAME_DELETE = 'team_game_delete',
  TEAM_GAME_ARCHIVE = 'team_game_archive',
  TEAM_GAME_UNARCHIVE = 'team_game_unarchive',
  TEAM_GAME_RETIRE = 'team_game_retire',
  TEAM_GAME_UNRETIRE = 'team_game_unretire',
  TEAM_GAME_SCORE_UPDATE = 'team_game_score_update',
  TEAM_MATCH_CREATE = 'team_match_create',
  TEAM_MATCH_DELETE = 'team_match_delete',
  TEAM_MATCH_ARCHIVE = 'team_match_archive',
  TEAM_MATCH_UNARCHIVE = 'team_match_unarchive',
  TEAM_MATCH_WINNER = 'team_match_winner',
  TEAM_MATCH_UNDO = 'team_match_undo',
  FINALS_CREATE = 'finals_create',
  FINALS_DELETE = 'finals_delete',
  FINALS_UPDATE = 'finals_update',
  FINALS_ARCHIVE = 'finals_archive',
  FINALS_UNARCHIVE = 'finals_unarchive',
  CONFIG_UPDATE = 'config_update'
}
